name: Metaphysics.io
description: A blog about technology and philosophy
url: http://metaphysics.io
markdown: redcarpet
pygments: true
permalink: none
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
